---
# ansible-playbook -i inventory/testing_inv -b -u filda --ask-pass --ask-become-pass playbooks/basic_config.yml --vault-password-file vaultPassword --extra-vars "@vault.yml"
- name: Zakladni konfigurace Ubuntu 24.04
  hosts: all
  become: yes
  vars:
    users:
      - username: filda
        home: /home/filda
      - username: root
        home: /root

  tasks:
    - name: Instalace HSTR a potrebnych balicku
      apt:
        name: hstr
        state: present
        update_cache: yes

    - name: Nastaveni casoveho pasma na Europe/Prague
      command: timedatectl set-timezone Europe/Prague

    - name: vytvoreni adresare pro dynamicke motd
      file:
        path: /etc/fildasecure
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: vytvoreni adresare pro dynamicke motd
      file:
        path: /etc/update-motd.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Nastaveni MOTD scriptu
      template:
        src: ../templates/motd-script.j2
        dest: /etc/update-motd.d/10-filda-secure
        owner: root
        group: root
        mode: '0755'

    - name: remove old motd
      file:
        path: /etc/motd
        state: absent

    - name: vytvoreni prazdneho motd pro generovani
      file:
        path: /etc/motd
        state: touch
        owner: root
        group: root
        mode: '0644'

    - name: Povoleni dynamickeho motd
      lineinfile:
        path: /etc/pam.d/sshd
        line: "session    optional     pam_motd.so  motd=/etc/motd"
        state: present

    - name: Zakazat default motd
      file:
        path: "/etc/update-motd.d/{{ item }}"
        mode: '0644'
      loop:
        - 00-header
        - 10-help-text
        - 50-landscape-sysinfo
        - 50-motd-news
        - 85-fwupd
        - 90-updates-available
        - 91-contract-ua-esm-status
        - 91-release-upgrade
        - 92-unattended-upgrades
        - 95-hwe-eol
        - 97-overlayroot
        - 98-fsck-at-reboot
        - 98-reboot-required

    # - name: Nastaveni MOTD
    #   template:
    #     src: ../templates/motd.j2
    #     dest: /etc/motd
    #     owner: root
    #     group: root
    #     mode: '0644'

    - name: Vytvoreni .config adresaru pro uzivatele
      file:
        path: "{{ item.home }}/.config"
        state: directory
        owner: "{{ item.username }}"
        group: "{{ item.username if item.username != 'root' else 'root' }}"
        mode: '0755'
      loop: "{{ users }}"

    - name: Vytvoreni .config/vim adresaru pro uzivatele
      file:
        path: "{{ item.home }}/.config/vim"
        state: directory
        owner: "{{ item.username }}"
        group: "{{ item.username if item.username != 'root' else 'root' }}"
        mode: '0755'
      loop: "{{ users }}"

    - name: Vytvoreni .config/tmux adresaru pro uzivatele
      file:
        path: "{{ item.home }}/.config/tmux"
        state: directory
        owner: "{{ item.username }}"
        group: "{{ item.username if item.username != 'root' else 'root' }}"
        mode: '0755'
      loop: "{{ users }}"

    - name: Nastaveni VIM konfigurace
      template:
        src: ../templates/vimrc.j2
        dest: "{{ item.home }}/.config/vim/vimrc"
        owner: "{{ item.username }}"
        group: "{{ item.username if item.username != 'root' else 'root' }}"
        mode: '0644'
      loop: "{{ users }}"

    - name: Aktivace VIM konfigurace
      blockinfile:
        path: "{{ item.home }}/.bashrc"
        block: |
          export VIMINIT="set nocp | source ${XDG_CONFIG_HOME:-$HOME/.config}/vim/vimrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - VIM"
        create: yes
        owner: "{{ item.username }}"
        group: "{{ item.username if item.username != 'root' else 'root' }}"
        mode: '0644'
      loop: "{{ users }}"

    - name: Nastaveni TMUX konfigurace
      template:
        src: ../templates/tmux.conf.j2
        dest: "{{ item.home }}/.config/tmux/tmux.conf"
        owner: "{{ item.username }}"
        group: "{{ item.username if item.username != 'root' else 'root' }}"
        mode: '0644'
      loop: "{{ users }}"

    - name: Aktivace TMUX konfigurace
      blockinfile:
        path: "{{ item.home }}/.bashrc"
        block: |
          export TMUX_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"
          alias tmux='tmux -f "$TMUX_CONFIG"'
        marker: "# {mark} ANSIBLE MANAGED BLOCK - TMUX"
        create: yes
        owner: "{{ item.username }}"
        group: "{{ item.username if item.username != 'root' else 'root' }}"
        mode: '0644'
      loop: "{{ users }}"

    - name: Pridani konfigurace HSTR do .bashrc
      blockinfile:
        path: "{{ item.home }}/.bashrc"
        block: |
          export HISTFILE={{ item.home }}/.bash_history
          export HISTCONTROL=ignorespace:erasedups
          export HISTFILESIZE=10000
          export HISTSIZE=10000
          export HISTTIMEFORMAT='%F %T '
          export HSTR_CONFIG=hicolor,raw-history-view
          bind '"\C-r": "\C-ahstr -- \C-j"'
          shopt -s histappend
        marker: "# {mark} ANSIBLE MANAGED BLOCK - HSTR"
        create: yes
        owner: "{{ item.username }}"
        group: "{{ item.username if item.username != 'root' else 'root' }}"
        mode: '0644'
      loop: "{{ users }}"
      
    - name: Nastaveni PS1 promptu pro uzivatele
      blockinfile:
        path: "{{ item.home }}/.bashrc"
        block: |
          {% if item.username == 'root' %}
          PS1='\[\e[38;5;202m\][\[\e[38;5;231m\]\t\[\e[38;5;202m\]] \[\e[38;5;52m\][\[\e[38;5;208m\]💀\u💀\[\e[38;5;52m\]@\[\e[38;5;208m\]\h\[\e[38;5;52m\]] \[\e[38;5;202m\]\w \[\e[38;5;208m\]❯ \[\e[0m\]'
          {% else %}
          PS1='\[\e[38;5;202m\][\[\e[38;5;231m\]\t\[\e[38;5;202m\]] \[\e[38;5;52m\][\[\e[38;5;208m\]\u\[\e[38;5;52m\]@\[\e[38;5;208m\]\h\[\e[38;5;52m\]] \[\e[38;5;202m\]\w \[\e[38;5;208m\]❯ \[\e[0m\]'
          {% endif %}
        marker: "# {mark} ANSIBLE MANAGED BLOCK - PS1 PROMPT"
        create: yes
        owner: "{{ item.username }}"
        group: "{{ item.username if item.username != 'root' else 'root' }}"
        mode: '0644'
      loop: "{{ users }}"