---
# ansible-playbook -i inventory/kvm_inventory -b -u filda --ask-pass --ask-become-pass playbooks/jump_kvm_setup.yml --vault-password-file vaultPassword --extra-vars "@vault.yml"
- name: Konfigurace jump serveru s Ansible a Semaphore
  hosts: kvm_jump_server
  become: yes
  vars:
    semaphore_version: "2.12.17"
    semaphore_config_path: /etc/semaphore
    semaphore_db_path: /var/lib/semaphore
    semaphore_user: semaphore
    semaphore_group: semaphore
    ansible_config_repo: "https://github.com/nemecfi/homeLabFilda.git"  # Změňte na váš Git repozitář
    ansible_config_dir: /opt/git
    semaphore_admin_user: admin
    semaphore_admin_password: "{{ vault_semaphore_admin_password }}"
    semaphore_admin_email: "admin@example.com"
    semaphore_database: semaphore
    semaphore_db_user: semaphore
    semaphore_db_password: "{{ vault_semaphore_db_password }}"

  tasks:
    - name: Aktualizace package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalace balicku
      apt:
        name:
          - git
          - curl
          - python3
          - python3-pip
          - python3-setuptools
          - python3-dev
          - build-essential
          - software-properties-common
          - apt-transport-https
          - ca-certificates
          - wget
          - gnupg
          - mariadb-server
          - python3-pymysql
        state: present

    - name: Instalace Ansible
      apt:
        name:
          - ansible
          - ansible-core
          - python3-pip
        state: latest
        update_cache: yes

    - name: Vytvoreni slozky pro ansible
      file:
        path: "{{ ansible_config_dir }}"
        state: directory
        mode: '0755'

    - name: Klonovani repa z gitu
      git:
        repo: "{{ ansible_config_repo }}"
        dest: "{{ ansible_config_dir }}"
        update: yes

    - name: Nastaveni promenne pro ansible CFG
      lineinfile:
        path: "/etc/environment"
        line: "ANSIBLE_CONFIG={{ ansible_config_dir }}/homeLabFilda/ansible.cfg"
        state: present

    # Konfigurace MariaDB pro Semaphore
    - name: Kontora sluzby mariadb
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Nastavení root hesla pro MariaDB
      mysql_user:
        name: root
        password: "{{ vault_mariadb_root_password }}"
        host_all: yes
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
      ignore_errors: yes
      no_log: true

    - name: Vytvoření databáze pro Semaphore
      mysql_db:
        name: "{{ semaphore_database }}"
        state: present
        login_user: root
        login_password: "{{ vault_mariadb_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Vytvoření uživatele MariaDB pro Semaphore
      mysql_user:
        name: "{{ semaphore_db_user }}"
        password: "{{ semaphore_db_password }}"
        priv: "{{ semaphore_database }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ vault_mariadb_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

    # Instalace Semaphore
    - name: Vytvoreni usera Semaphore
      user:
        name: "{{ semaphore_user }}"
        groups: sudo
        shell: /bin/bash
        create_home: yes
        system: yes

    - name: Vytvoreni adresaru pro Semaphore
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ semaphore_user }}"
        group: "{{ semaphore_group }}"
        mode: '0755'
      with_items:
        - "{{ semaphore_config_path }}"
        - "{{ semaphore_db_path }}"

    - name: Stazeni Semaphore z gitu
      get_url:
        url: "https://github.com/ansible-semaphore/semaphore/releases/download/v{{ semaphore_version }}/semaphore_{{ semaphore_version }}_linux_amd64.tar.gz"
        dest: /tmp/semaphore.tar.gz
        mode: '0644'

    - name: Rozbaleni Semaphore
      unarchive:
        src: /tmp/semaphore.tar.gz
        dest: /usr/local/bin
        remote_src: yes
        mode: '0755'
        owner: "{{ semaphore_user }}"
        group: "{{ semaphore_group }}"

    - name: clear tmp
      file:
        path: /tmp/semaphore.tar.gz
        state: absent

    - name: Vytvoreni semaphore configraku
      template:
        src: ../templates/semaphore-config.json.j2
        dest: "{{ semaphore_config_path }}/config.json"
        owner: "{{ semaphore_user }}"
        group: "{{ semaphore_group }}"
        mode: '0644'
      notify: restart semaphore
    # Nefunguje, musi se opravit
    - name: Nastaveni Semaphore
      expect:
        command: sudo -u {{ semaphore_user }} /usr/local/bin/semaphore setup --config {{ semaphore_config_path }}/config.json
        responses:
          '\(default 1\):': '1'
          'db Hostname \(default 127.0.0.1:3306\):': '127.0.0.1:3306'
          'db User \(default root\):': '{{ semaphore_db_user }}'
          'db Password:': '{{ semaphore_db_password }}'
          'db Name \(default semaphore\):': '{{ semaphore_database }}'
          'Playbook path \(default /tmp/semaphore\):': '/tmp/semaphore'
          'Public URL \(optional.*\):': ''
          'Enable email alerts\? \(yes/no\) \(default no\):': 'no'
          'Enable telegram alerts\? \(yes/no\) \(default no\):': 'no'
          'Enable slack alerts\? \(yes/no\) \(default no\):': 'no'
          'Enable Rocket.Chat alerts\? \(yes/no\) \(default no\):': 'no'
          'Enable Microsoft Team Channel alerts\? \(yes/no\) \(default no\):': 'no'
          'Enable LDAP authentication\? \(yes/no\) \(default no\):': 'no'
          'Admin username:': '{{ semaphore_admin_user }}'
          'Admin password:': '{{ semaphore_admin_password }}'
          'Admin email:': '{{ semaphore_admin_email }}'
          'Confirm admin password:': '{{ semaphore_admin_password }}'
      args:
        creates: "{{ semaphore_config_path }}/.setup_complete"
      # no_log: true

    - name: Vytvoreni sluzby pro semaphore
      copy:
        dest: /etc/systemd/system/semaphore.service
        content: |
          [Unit]
          Description=Ansible Semaphore
          Documentation=https://github.com/ansible-semaphore/semaphore
          After=network.target
          After=mariadb.service
          
          [Service]
          Type=simple
          User={{ semaphore_user }}
          Group={{ semaphore_group }}
          ExecStart=/usr/local/bin/semaphore server --config {{ semaphore_config_path }}/config.json
          Restart=on-failure
          RestartSec=10
          
          [Install]
          WantedBy=multi-user.target
        mode: '0644'
      notify: 
        - reload systemd
        - restart semaphore

    - name: check jestli semaphore bezi
      service:
        name: semaphore
        state: started
        enabled: yes

    - name: Setup complete file
      file:
        path: "{{ semaphore_config_path }}/.setup_complete"
        state: touch
        owner: "{{ semaphore_user }}"
        group: "{{ semaphore_group }}"
        mode: '0644'

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes

    - name: restart semaphore
      service:
        name: semaphore
        state: restarted