---
# ansible-playbook -i inventory/kvm_host -b -u filda --ask-pass --ask-become-pass playbooks/kvm_setup.yml --vault-password-file vaultPassword --extra-vars "@vault.yml"
- name: Konfigurace jump serveru s Ansible a Semaphore
  hosts: jump_server
  become: yes
  vars:
    semaphore_version: "2.12.17"
    semaphore_config_path: /etc/semaphore
    semaphore_db_path: /var/lib/semaphore
    semaphore_user: semaphore
    semaphore_group: semaphore
    ansible_config_repo: "https://github.com/username/ansible-config.git"  # Změňte na váš Git repozitář
    ansible_config_dir: /opt/git
    semaphore_admin_user: admin
    semaphore_admin_password: "{{ vault_semaphore_admin_password }}"
    semaphore_admin_email: "admin@example.com"
    semaphore_database: semaphore
    semaphore_db_user: semaphore
    semaphore_db_password: "{{ vault_semaphore_db_password }}"

  tasks:
    - name: Aktualizace package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalace závislostí
      apt:
        name:
          - git
          - curl
          - python3
          - python3-pip
          - python3-setuptools
          - python3-dev
          - build-essential
          - software-properties-common
          - apt-transport-https
          - ca-certificates
          - wget
          - gnupg
          - mariadb-server
        state: present

    # Konfigurace Ansible
    - name: Přidání Ansible PPA repozitáře
      apt_repository:
        repo: ppa:ansible/ansible

    - name: Instalace Ansible přes apt
      apt:
        name: ansible
        state: latest
        update_cache: yes

    - name: Vytvoření adresáře pro Ansible konfiguraci
      file:
        path: "{{ ansible_config_dir }}"
        state: directory
        mode: '0755'

    - name: Klonování repozitáře s Ansible konfigurací
      git:
        repo: "{{ ansible_config_repo }}"
        dest: "{{ ansible_config_dir }}"
        update: yes

    - name: Nastavení proměnné prostředí ANSIBLE_CONFIG globálně
      lineinfile:
        path: "/etc/environment"
        line: "ANSIBLE_CONFIG={{ ansible_config_dir }}/ansible.cfg"
        state: present

    - name: Vytvoření adresáře pro Ansible log
      file:
        path: /var/log
        state: directory
        mode: '0755'

    - name: Vytvoření Ansible log souboru
      file:
        path: /var/log/ansible.log
        state: touch
        mode: '0644'

    # Konfigurace MariaDB pro Semaphore
    - name: Zajištění, že MariaDB služba běží
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Nastavení root hesla pro MariaDB
      mysql_user:
        name: root
        password: "{{ vault_mariadb_root_password }}"
        host_all: yes
        state: present
      no_log: true

    - name: Vytvoření databáze pro Semaphore
      mysql_db:
        name: "{{ semaphore_database }}"
        state: present
        login_user: root
        login_password: "{{ vault_mariadb_root_password }}"

    - name: Vytvoření uživatele MariaDB pro Semaphore
      mysql_user:
        name: "{{ semaphore_db_user }}"
        password: "{{ semaphore_db_password }}"
        priv: "{{ semaphore_database }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ vault_mariadb_root_password }}"
      no_log: true

    # Instalace Semaphore
    - name: Vytvoření uživatele Semaphore
      user:
        name: "{{ semaphore_user }}"
        groups: sudo
        shell: /bin/bash
        create_home: yes
        system: yes

    - name: Vytvoření adresářů pro Semaphore
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ semaphore_user }}"
        group: "{{ semaphore_group }}"
        mode: '0755'
      with_items:
        - "{{ semaphore_config_path }}"
        - "{{ semaphore_db_path }}"

    - name: Stažení Semaphore
      get_url:
        url: "https://github.com/ansible-semaphore/semaphore/releases/download/v{{ semaphore_version }}/semaphore_{{ semaphore_version }}_linux_amd64.tar.gz"
        dest: /tmp/semaphore.tar.gz
        mode: '0644'

    - name: Rozbalení Semaphore
      unarchive:
        src: /tmp/semaphore.tar.gz
        dest: /usr/local/bin
        remote_src: yes
        mode: '0755'
        owner: "{{ semaphore_user }}"
        group: "{{ semaphore_group }}"

    - name: Vyčištění stažených souborů
      file:
        path: /tmp/semaphore.tar.gz
        state: absent

    - name: Vytvoření Semaphore konfiguračního souboru
      template:
        src: templates/semaphore-config.json.j2
        dest: "{{ semaphore_config_path }}/config.json"
        owner: "{{ semaphore_user }}"
        group: "{{ semaphore_group }}"
        mode: '0644'
      notify: restart semaphore

    - name: Nastavení Semaphore
      shell: |
        /usr/local/bin/semaphore setup --config {{ semaphore_config_path }}/config.json << EOF
        {{ semaphore_db_user }}
        {{ semaphore_db_password }}
        {{ semaphore_database }}
        127.0.0.1:3306
        {{ semaphore_admin_user }}
        {{ semaphore_admin_email }}
        {{ semaphore_admin_password }}
        EOF
      args:
        creates: "{{ semaphore_config_path }}/.setup_complete"
      become: yes
      become_user: "{{ semaphore_user }}"
      no_log: true

    - name: Vytvoření service souboru pro Semaphore
      copy:
        dest: /etc/systemd/system/semaphore.service
        content: |
          [Unit]
          Description=Ansible Semaphore
          Documentation=https://github.com/ansible-semaphore/semaphore
          After=network.target
          After=mariadb.service
          
          [Service]
          Type=simple
          User={{ semaphore_user }}
          Group={{ semaphore_group }}
          ExecStart=/usr/local/bin/semaphore server --config {{ semaphore_config_path }}/config.json
          Restart=on-failure
          RestartSec=10
          
          [Install]
          WantedBy=multi-user.target
        mode: '0644'
      notify: 
        - reload systemd
        - restart semaphore

    - name: Zajištění, že Semaphore služba běží
      service:
        name: semaphore
        state: started
        enabled: yes

    # Konfigurace firewallu odstraněna podle požadavku

    - name: Vytvoření příznakového souboru pro dokončení instalace
      file:
        path: "{{ semaphore_config_path }}/.setup_complete"
        state: touch
        owner: "{{ semaphore_user }}"
        group: "{{ semaphore_group }}"
        mode: '0644'

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes

    - name: restart semaphore
      service:
        name: semaphore
        state: restarted